FROM python:3.11-slim


RUN apt-get update && apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential git \
    && rm -rf /var/lib/apt/lists/*


ARG GO_VERSION=1.22.5
RUN wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz -O /tmp/go.tgz \
    && tar -C /usr/local -xzf /tmp/go.tgz \
    && rm /tmp/go.tgz
ENV PATH="/usr/local/go/bin:/root/go/bin:${PATH}"


RUN go install github.com/projectdiscovery/katana/cmd/katana@latest

WORKDIR /app


COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


COPY app /app/app

ENV FLASK_APP=app
ENV PYTHONUNBUFFERED=1

EXPOSE 5000

# API konteyneri için default komut (compose içinde override ediliyor)
CMD ["flask","run","--host=0.0.0.0","--port=5000"]
